package constant

const (
	MACHINERY_TASK_CONSUME                            = "MACHINERY_TASK_CONSUME"
	MACHINERY_TASK_NAME_WORK_ORDER_SEND_OVER_TIME_MSG = "WORK_ORDER_SEND_OVER_TIME_MSG"
	MACHINERY_TASK_NAME_UPDATE_HOMEPAGE_GROUP         = "UPDATE_HOMEPAGE_GROUP"
	MACHINERY_TASK_NAME_UPDATE_HOMEPAGE_COMPANY       = "UPDATE_HOMEPAGE_COMPANY"
)
