package constant

const (
	STAFF_MESSAGE_CATEGORY_INNER_NOTICE   = 1 //内部通知
	STAFF_MESSAGE_CATEGORY_DISPATCH_ORDER = 2 //工单消息

	STAFF_MESSAGE_STATUS_SENDED = 1 //已发送
	STAFF_MESSAGE_STATUS_READED = 2 //已阅读
)
